import { jsPDF } from 'jspdf';

/**
 * Generate a professional PDF for Questions (PYQs or Mock Tests)
 */
export const generateQuestionPdf = (title, subtitle, questions, filename = 'document.pdf') => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 20;
  const contentWidth = pageWidth - 2 * margin;
  let cursorY = margin;

  // Header Branding
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(22);
  doc.setTextColor(244, 117, 33); // Saffron color like the app
  doc.text('Sarkari Exam AI', margin, cursorY);
  cursorY += 10;

  doc.setFontSize(10);
  doc.setTextColor(100);
  doc.setFont('helvetica', 'italic');
  doc.text('Your Personal AI Exam Coach', margin, cursorY);
  cursorY += 15;

  // Title
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(16);
  doc.setTextColor(0);
  const splitTitle = doc.splitTextToSize(title, contentWidth);
  doc.text(splitTitle, margin, cursorY);
  cursorY += splitTitle.length * 8;

  // Subtitle (Exam/Year)
  if (subtitle) {
    doc.setFontSize(12);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(80);
    doc.text(subtitle, margin, cursorY);
    cursorY += 10;
  }

  // Divider
  doc.setDrawColor(230);
  doc.line(margin, cursorY, pageWidth - margin, cursorY);
  cursorY += 15;

  // Questions
  questions.forEach((q, index) => {
    // Check page overflow
    if (cursorY > pageHeight - 30) {
      doc.addPage();
      cursorY = margin;
    }

    // Question Text
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(12);
    doc.setTextColor(0);
    const qText = `Q${index + 1}. ${q.question}`;
    const splitQText = doc.splitTextToSize(qText, contentWidth);
    doc.text(splitQText, margin, cursorY);
    cursorY += splitQText.length * 7;

    // Options
    if (q.options && Array.isArray(q.options)) {
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(11);
      doc.setTextColor(60);
      q.options.forEach((opt, optIdx) => {
        if (cursorY > pageHeight - 20) {
          doc.addPage();
          cursorY = margin;
        }
        const optLetter = String.fromCharCode(65 + optIdx);
        const optText = `   ${optLetter}) ${opt}`;
        const splitOptText = doc.splitTextToSize(optText, contentWidth - 10);
        doc.text(splitOptText, margin, cursorY);
        cursorY += splitOptText.length * 6;
      });
    }

    // Correct Answer & Explanation
    if (q.correctAnswer || q.explanation) {
      cursorY += 3;
      if (cursorY > pageHeight - 20) {
        doc.addPage();
        cursorY = margin;
      }
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(0, 150, 0); // Green for answer
      if (q.correctAnswer) {
        doc.text(`Correct Answer: ${q.correctAnswer}`, margin + 5, cursorY);
        cursorY += 7;
      }
      
      if (q.explanation) {
        doc.setFont('helvetica', 'italic');
        doc.setFontSize(10);
        doc.setTextColor(100);
        const expText = `Explanation: ${q.explanation}`;
        const splitExp = doc.splitTextToSize(expText, contentWidth - 10);
        doc.text(splitExp, margin + 5, cursorY);
        cursorY += splitExp.length * 6;
      }
    }

    cursorY += 10; // Space between questions
  });

  // Footer on all pages
  const pageCount = doc.internal.getNumberOfPages();
  for(let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(10);
    doc.setTextColor(150);
    doc.text(`Page ${i} of ${pageCount} | Generated by Sarkari Exam AI`, pageWidth / 2, pageHeight - 10, { align: 'center' });
  }

  doc.save(filename);
};

/**
 * Generate a professional PDF for Study Notes
 */
export const generateNotesPdf = (title, content, filename = 'notes.pdf') => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 20;
  const contentWidth = pageWidth - 2 * margin;
  let cursorY = margin;

  // Header Branding
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(22);
  doc.setTextColor(244, 117, 33);
  doc.text('Sarkari Exam AI', margin, cursorY);
  cursorY += 10;

  doc.setFontSize(10);
  doc.setTextColor(100);
  doc.setFont('helvetica', 'italic');
  doc.text('Study Notes | Elevate Your Learning', margin, cursorY);
  cursorY += 15;

  // Title
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(18);
  doc.setTextColor(0);
  const splitTitle = doc.splitTextToSize(title, contentWidth);
  doc.text(splitTitle, margin, cursorY);
  cursorY += splitTitle.length * 10;

  // Divider
  doc.setDrawColor(244, 117, 33);
  doc.setLineWidth(1);
  doc.line(margin, cursorY, pageWidth - margin, cursorY);
  cursorY += 15;

  // Content (Markdown-like processing for basic bold/bullets)
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(11);
  doc.setTextColor(60);

  // Simple split by newline and wrap
  const lines = content.split('\n');
  lines.forEach(line => {
    if (cursorY > pageHeight - 20) {
      doc.addPage();
      cursorY = margin;
    }

    let text = line.trim();
    if (!text) {
      cursorY += 5; // Paragraph space
      return;
    }

    // Basic Header Detection
    if (text.startsWith('#')) {
      const level = (text.match(/^#+/) || [''])[0].length;
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(16 - level);
      text = text.replace(/^#+\s*/, '');
      const split = doc.splitTextToSize(text, contentWidth);
      doc.text(split, margin, cursorY);
      cursorY += split.length * 10;
      doc.setFontSize(11);
      doc.setFont('helvetica', 'normal');
    } else if (text.startsWith('* ') || text.startsWith('- ')) {
      // Bullets
      doc.setFont('helvetica', 'normal');
      text = `  • ${text.substring(2)}`;
      const split = doc.splitTextToSize(text, contentWidth - 5);
      doc.text(split, margin, cursorY);
      cursorY += split.length * 6;
    } else {
      // Normal text
      const split = doc.splitTextToSize(text, contentWidth);
      doc.text(split, margin, cursorY);
      cursorY += split.length * 6;
    }
  });

  // Footer
  const pageCount = doc.internal.getNumberOfPages();
  for(let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(10);
    doc.setTextColor(150);
    doc.text(`Page ${i} of ${pageCount} | Sarkari Exam AI Study Material`, pageWidth / 2, pageHeight - 10, { align: 'center' });
  }

  doc.save(filename);
};
