import { jsPDF } from 'jspdf';

/**
 * Generate a professional PDF for Questions (PYQs or Mock Tests)
 */
export const generateQuestionPdf = (title, subtitle, questions, filename = 'document.pdf') => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 20;
  const contentWidth = pageWidth - 2 * margin;
  let cursorY = margin;

  // Header Branding
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(22);
  doc.setTextColor(244, 117, 33); // Saffron color like the app
  doc.text('Sarkari Exam AI', margin, cursorY);
  cursorY += 10;

  doc.setFontSize(10);
  doc.setTextColor(100);
  doc.setFont('helvetica', 'italic');
  doc.text('Your Personal AI Exam Coach', margin, cursorY);
  cursorY += 15;

  // Title
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(16);
  doc.setTextColor(0);
  const splitTitle = doc.splitTextToSize(title, contentWidth);
  doc.text(splitTitle, margin, cursorY);
  cursorY += splitTitle.length * 8;

  // Subtitle (Exam/Year)
  if (subtitle) {
    doc.setFontSize(12);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(80);
    doc.text(subtitle, margin, cursorY);
    cursorY += 10;
  }

  // Divider
  doc.setDrawColor(230);
  doc.line(margin, cursorY, pageWidth - margin, cursorY);
  cursorY += 15;

  // Questions
  questions.forEach((q, index) => {
    // Check page overflow
    if (cursorY > pageHeight - 30) {
      doc.addPage();
      cursorY = margin;
    }

    // Question Text
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(12);
    doc.setTextColor(0);
    const qText = `Q${index + 1}. ${q.question}`;
    const splitQText = doc.splitTextToSize(qText, contentWidth);
    doc.text(splitQText, margin, cursorY);
    cursorY += splitQText.length * 7;

    // Options
    if (q.options && Array.isArray(q.options)) {
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(11);
      doc.setTextColor(60);
      q.options.forEach((opt, optIdx) => {
        if (cursorY > pageHeight - 20) {
          doc.addPage();
          cursorY = margin;
        }
        const optLetter = String.fromCharCode(65 + optIdx);
        const optText = `   ${optLetter}) ${opt}`;
        const splitOptText = doc.splitTextToSize(optText, contentWidth - 10);
        doc.text(splitOptText, margin, cursorY);
        cursorY += splitOptText.length * 6;
      });
    }

    // Correct Answer & Explanation
    if (q.correctAnswer || q.explanation) {
      cursorY += 3;
      if (cursorY > pageHeight - 20) {
        doc.addPage();
        cursorY = margin;
      }
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(0, 150, 0); // Green for answer
      if (q.correctAnswer) {
        doc.text(`Correct Answer: ${q.correctAnswer}`, margin + 5, cursorY);
        cursorY += 7;
      }
      
      if (q.explanation) {
        doc.setFont('helvetica', 'italic');
        doc.setFontSize(10);
        doc.setTextColor(100);
        const expText = `Explanation: ${q.explanation}`;
        const splitExp = doc.splitTextToSize(expText, contentWidth - 10);
        doc.text(splitExp, margin + 5, cursorY);
        cursorY += splitExp.length * 6;
      }
    }

    cursorY += 10; // Space between questions
  });

  // Footer on all pages
  const pageCount = doc.internal.getNumberOfPages();
  for(let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(10);
    doc.setTextColor(150);
    doc.text(`Page ${i} of ${pageCount} | Generated by Sarkari Exam AI`, pageWidth / 2, pageHeight - 10, { align: 'center' });
  }

  doc.save(filename);
};

import html2pdf from 'html2pdf.js';
import { marked } from 'marked';

/**
 * Generate a high quality, natively formatted PDF for Study Notes / Output text using html2pdf
 * Solves jsPDF limitations with Hindi, Emojis, and Markdown.
 */
export const generateNotesPdf = (title, content, filename = 'notes.pdf') => {
  const container = document.createElement('div');
  container.style.padding = '40px';
  container.style.fontFamily = `'Segoe UI', Roboto, Helvetica, Arial, sans-serif`;
  container.style.color = '#1f2937';
  container.style.lineHeight = '1.6';
  container.style.backgroundColor = '#ffffff';

  // Branding Header
  const headerHtml = `
    <div style="border-bottom: 2px solid #f47521; padding-bottom: 12px; margin-bottom: 24px;">
      <h1 style="color: #f47521; margin: 0 0 4px 0; font-size: 28px;">Sarkari Exam AI</h1>
      <p style="color: #6b7280; font-style: italic; margin: 0; font-size: 14px;">Study Notes | Elevate Your Learning</p>
    </div>
    <h2 style="font-size: 24px; color: #111827; margin-top: 0; margin-bottom: 16px;">${title}</h2>
  `;

  // Parse markdown securely into HTML
  const parsedMarkdown = marked.parse(content);
  
  // Format body
  const bodyHtml = `
    <div style="font-size: 14px;">
      ${parsedMarkdown}
    </div>
  `;

  container.innerHTML = headerHtml + bodyHtml;
  
  // Scoped CSS for markdown styling so it prints beautiful bold, lists, etc.
  const style = document.createElement('style');
  style.textContent = `
    h1, h2, h3, h4 { color: #111827; font-weight: 600; margin-top: 1.5em; margin-bottom: 0.5em; }
    p { margin-bottom: 1em; }
    ul, ol { padding-left: 24px; margin-bottom: 1em; }
    li { margin-bottom: 0.25em; }
    strong, b { color: #f47521; font-weight: 700; }
    code { background: #f3f4f6; padding: 2px 4px; border-radius: 4px; font-family: monospace; font-size: 0.9em; }
    pre { background: #f3f4f6; padding: 12px; border-radius: 8px; overflow-x: auto; }
  `;
  container.appendChild(style);

  // CRITICAL FOR MOBILE: Append to body to ensure capture works correctly
  container.style.position = 'fixed';
  container.style.left = '-9999px';
  container.style.top = '0';
  container.style.width = '800px'; // Force static width for consistent rendering
  container.style.zIndex = '-1';
  document.body.appendChild(container);

  // Generate the PDF from HTML directly
  const opt = {
    margin: [10, 10, 15, 10], // top, left, bottom, right
    filename: filename,
    image: { type: 'jpeg', quality: 0.98 },
    html2canvas: { scale: 2, useCORS: true, letterRendering: true, logging: false },
    jsPDF: { unit: 'mm', format: 'a4', orientation: 'portrait' }
  };

  html2pdf().set(opt).from(container).toPdf().get('pdf').output('blob').then((blob) => {
    // Manual download trigger for mobile compatibility
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = filename;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
    
    // Clean up container
    document.body.removeChild(container);
  }).catch(err => {
    console.error('PDF Generation Error:', err);
    if (container.parentNode) {
      document.body.removeChild(container);
    }
  });
};
