import { jsPDF } from 'jspdf';

/**
 * Generate a professional PDF for Questions (PYQs or Mock Tests)
 */
export const generateQuestionPdf = (title, subtitle, questions, filename = 'document.pdf') => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 20;
  const contentWidth = pageWidth - 2 * margin;
  let cursorY = margin;

  // Header Branding
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(22);
  doc.setTextColor(244, 117, 33); // Saffron color like the app
  doc.text('Sarkari Exam AI', margin, cursorY);
  cursorY += 10;

  doc.setFontSize(10);
  doc.setTextColor(100);
  doc.setFont('helvetica', 'italic');
  doc.text('Your Personal AI Exam Coach', margin, cursorY);
  cursorY += 15;

  // Title
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(16);
  doc.setTextColor(0);
  const splitTitle = doc.splitTextToSize(title, contentWidth);
  doc.text(splitTitle, margin, cursorY);
  cursorY += splitTitle.length * 8;

  // Subtitle (Exam/Year)
  if (subtitle) {
    doc.setFontSize(12);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(80);
    doc.text(subtitle, margin, cursorY);
    cursorY += 10;
  }

  // Divider
  doc.setDrawColor(230);
  doc.line(margin, cursorY, pageWidth - margin, cursorY);
  cursorY += 15;

  // Questions
  questions.forEach((q, index) => {
    // Check page overflow
    if (cursorY > pageHeight - 30) {
      doc.addPage();
      cursorY = margin;
    }

    // Question Text
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(12);
    doc.setTextColor(0);
    const qText = `Q${index + 1}. ${q.question}`;
    const splitQText = doc.splitTextToSize(qText, contentWidth);
    doc.text(splitQText, margin, cursorY);
    cursorY += splitQText.length * 7;

    // Options
    if (q.options && Array.isArray(q.options)) {
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(11);
      doc.setTextColor(60);
      q.options.forEach((opt, optIdx) => {
        if (cursorY > pageHeight - 20) {
          doc.addPage();
          cursorY = margin;
        }
        const optLetter = String.fromCharCode(65 + optIdx);
        const optText = `   ${optLetter}) ${opt}`;
        const splitOptText = doc.splitTextToSize(optText, contentWidth - 10);
        doc.text(splitOptText, margin, cursorY);
        cursorY += splitOptText.length * 6;
      });
    }

    // Correct Answer & Explanation
    if (q.correctAnswer || q.explanation) {
      cursorY += 3;
      if (cursorY > pageHeight - 20) {
        doc.addPage();
        cursorY = margin;
      }
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(0, 150, 0); // Green for answer
      if (q.correctAnswer) {
        doc.text(`Correct Answer: ${q.correctAnswer}`, margin + 5, cursorY);
        cursorY += 7;
      }
      
      if (q.explanation) {
        doc.setFont('helvetica', 'italic');
        doc.setFontSize(10);
        doc.setTextColor(100);
        const expText = `Explanation: ${q.explanation}`;
        const splitExp = doc.splitTextToSize(expText, contentWidth - 10);
        doc.text(splitExp, margin + 5, cursorY);
        cursorY += splitExp.length * 6;
      }
    }

    cursorY += 10; // Space between questions
  });

  // Footer on all pages
  const pageCount = doc.internal.getNumberOfPages();
  for(let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(10);
    doc.setTextColor(150);
    doc.text(`Page ${i} of ${pageCount} | Generated by Sarkari Exam AI`, pageWidth / 2, pageHeight - 10, { align: 'center' });
  }

  // If running in Flutter App WebView, send via JS Bridge
  if (window.FlutterDownload) {
    const base64String = doc.output('datauristring').split(',')[1];
    window.FlutterDownload.postMessage(JSON.stringify({
      data: base64String,
      fileName: filename
    }));
  } else {
    // Standard download — works on desktop and modern mobile browsers
    const blob = doc.output('blob');
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    setTimeout(() => { URL.revokeObjectURL(url); document.body.removeChild(a); }, 1000);
  }
};

/**
 * Generate a highly reliable natively drawn PDF for Study Notes
 * Ensures 100% compatibility across Mobile (iOS/Safari) and Desktop platforms.
 */
export const generateNotesPdf = (title, content, filename = 'notes.pdf') => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 20;
  const contentWidth = pageWidth - 2 * margin;
  let cursorY = margin;

  // Function to add a new page horizontally
  const checkPageBreak = (spaceNeeded = 10) => {
    if (cursorY + spaceNeeded > pageHeight - margin) {
      doc.addPage();
      cursorY = margin;
      return true;
    }
    return false;
  };

  // Header Branding (Consistent with Questions PDF)
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(22);
  doc.setTextColor(244, 117, 33); // Saffron color
  doc.text('Sarkari Exam AI', margin, cursorY);
  cursorY += 10;

  doc.setFontSize(10);
  doc.setTextColor(100);
  doc.setFont('helvetica', 'italic');
  doc.text('Your Personal AI Exam Coach | Study Notes', margin, cursorY);
  cursorY += 15;

  // Title
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(16);
  doc.setTextColor(0);
  const splitTitle = doc.splitTextToSize(title, contentWidth);
  doc.text(splitTitle, margin, cursorY);
  cursorY += splitTitle.length * 8 + 5;

  // Divider
  doc.setDrawColor(230);
  doc.line(margin, cursorY, pageWidth - margin, cursorY);
  cursorY += 15;

  // Basic Markdown Parser for Native jsPDF Draw
  if (!content || typeof content !== 'string') {
    doc.text("No content available to export.", margin, cursorY);
  } else {
    // Clean string from markdown code blocks
    let cleanText = content.replace(/```[\s\S]*?```/g, (match) => {
      // Just strip the backticks for inline viewing
      return match.replace(/```[a-z]*\n?/g, '').trim();
    });

    const lines = cleanText.split('\n');
    let inList = false;

    lines.forEach(line => {
      const trimmed = line.trim();
      if (!trimmed) {
        cursorY += 4; // Add slight paragraph spacing
        checkPageBreak();
        return;
      }

      // Check for Headers (# Header)
      const headerMatch = trimmed.match(/^(#{1,6})\s+(.*)$/);
      if (headerMatch) {
         const level = headerMatch[1].length;
         doc.setFont('helvetica', 'bold');
         doc.setTextColor(0);
         const fontSize = level === 1 ? 16 : (level === 2 ? 14 : 12);
         doc.setFontSize(fontSize);
         
         const textObj = doc.splitTextToSize(headerMatch[2].replace(/\*\*/g, ''), contentWidth);
         checkPageBreak(textObj.length * (fontSize/2));
         
         cursorY += 4; // Spacing before header
         doc.text(textObj, margin, cursorY);
         cursorY += textObj.length * (fontSize/1.5) + 4;
         return;
      }

      // Check for List Items (- or * or 1.)
      const listMatch = trimmed.match(/^([-*]|\d+\.)\s+(.*)$/);
      if (listMatch) {
        doc.setFont('helvetica', 'normal');
        doc.setFontSize(11);
        doc.setTextColor(40);
        
        const bulletType = listMatch[1];
        let textContent = listMatch[2];
        
        // Remove bold asterisks for native display
        textContent = textContent.replace(/\*\*/g, '');
        
        const textObj = doc.splitTextToSize(textContent, contentWidth - 8); // Account for indent
        checkPageBreak(textObj.length * 6);
        
        doc.text(`${bulletType} `, margin, cursorY);
        doc.text(textObj, margin + 8, cursorY);
        cursorY += textObj.length * 5.5 + 2;
        return;
      }

      // Regular Text (Paragraph)
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(11);
      doc.setTextColor(40);
      
      // Remove arbitrary bold formatting asterisks for cleaner text notes
      let regularText = trimmed.replace(/\*\*/g, '').replace(/\*/g, '').replace(/__/g, '');
      
      const textObj = doc.splitTextToSize(regularText, contentWidth);
      checkPageBreak(textObj.length * 6);
      
      doc.text(textObj, margin, cursorY);
      cursorY += textObj.length * 5.5;
    });
  }

  // Footer on all pages
  const pageCount = doc.internal.getNumberOfPages();
  for(let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(9);
    doc.setTextColor(150);
    doc.text(`Page ${i} of ${pageCount} | Generated by Sarkari Exam AI`, pageWidth / 2, pageHeight - 10, { align: 'center' });
  }

  // If running in Flutter App WebView, send via JS Bridge
  if (window.FlutterDownload) {
    const base64String = doc.output('datauristring').split(',')[1];
    window.FlutterDownload.postMessage(JSON.stringify({
      data: base64String,
      fileName: filename
    }));
  } else {
    // Standard download — works on desktop and modern mobile browsers
    const blob = doc.output('blob');
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    setTimeout(() => { URL.revokeObjectURL(url); document.body.removeChild(a); }, 1000);
  }
};
