name: sarkari_exam_ai_app
description: Sarkari Exam AI Official Mobile App.
publish_to: 'none'
version: 1.0.7+8

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.8.0
  http: ^1.1.0
  url_launcher: ^6.2.1
  path_provider: ^2.1.1
  open_file: ^3.3.2
  permission_handler: ^11.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
